## **今天根据PyTorch教程中的60min Blitz走一遭**

### What is PyTorch?
#### Tensors

In [2]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
from __future__ import print_function
import torch

创建一个空矩阵（未初始化，数值保持被分配地址的数值）

In [4]:
x=torch.empty(5,3)
print(x)

tensor([[1.0469e-38, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39]])


创建随机初始化的矩阵

In [5]:
x=torch.rand(5,3)
print(x)

tensor([[0.1519, 0.9682, 0.8162],
        [0.3169, 0.7028, 0.7007],
        [0.3944, 0.4533, 0.7516],
        [0.1279, 0.0949, 0.5553],
        [0.2158, 0.7944, 0.6705]])


创建全零矩阵，dtype为long

In [6]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


根据数据直接创建张量（***Tensor***）

In [7]:
x=torch.tensor([[5,9.0],[66,77.8]])
print(x)

tensor([[ 5.0000,  9.0000],
        [66.0000, 77.8000]])


仿照现有tensor创建tensor（*两tensor属性相同,除非设置新的值进行覆盖*）

In [8]:
print(x)
x=x.new_ones(5,3,2,dtype=torch.double)
y=torch.tensor(14)#缺少该行则报错，new_*方法需要提前声明tensor类型的变量
y=y.new_zeros(2,4)
print(x)
print(y)
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 5.0000,  9.0000],
        [66.0000, 77.8000]])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]], dtype=torch.float64)
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[[-0.3747, -1.4815],
         [ 0.4486,  0.9287],
         [-0.8822,  0.4818]],

        [[-0.5050,  1.4398],
         [ 1.2312, -1.3355],
         [-2.4318,  0.8880]],

        [[ 2.1469, -1.5794],
         [-2.0000, -0.4654],
         [ 1.2671,  1.1716]],

        [[-1.7897,  0.8424],
         [ 0.2663,  1.6071],
         [ 1.4577,  1.3513]],

        [[-0.5458,  2.4517],
         [ 0.0111,  0.6618],
         [ 0.9433, -0.6245]]])


**上例中采用new_*方法创建对象（参数包括size），当前尚不清楚该方法具体内容,但预计该方法为tensor变量的方法，须先声明tensor对象**

获取Size，*输出的torch.size实际上是**元组（tuple）**，支持所有元组操作，元组是一种不可变序列*

In [9]:
print(x.size())
print(sum(x.size()))
print(list(x.size()))

torch.Size([5, 3, 2])
10
[5, 3, 2]


#### Operations
#### 三种加法运算

##### 两个运算对象

In [10]:
x=torch.ones(5,3)
print(x)
y=torch.rand(5,3)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8134, 0.6335, 0.5455],
        [0.9205, 0.1435, 0.8571],
        [0.9714, 0.1670, 0.6440],
        [0.4752, 0.9067, 0.4434],
        [0.3311, 0.3418, 0.5698]])


##### 语法1

In [11]:
print(x+y)

tensor([[1.8134, 1.6335, 1.5455],
        [1.9205, 1.1435, 1.8571],
        [1.9714, 1.1670, 1.6440],
        [1.4752, 1.9067, 1.4434],
        [1.3311, 1.3418, 1.5698]])


##### 语法2

In [12]:
print(torch.add(x,y))

tensor([[1.8134, 1.6335, 1.5455],
        [1.9205, 1.1435, 1.8571],
        [1.9714, 1.1670, 1.6440],
        [1.4752, 1.9067, 1.4434],
        [1.3311, 1.3418, 1.5698]])


语法2可指定add函数输出到特定对象

In [13]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.8134, 1.6335, 1.5455],
        [1.9205, 1.1435, 1.8571],
        [1.9714, 1.1670, 1.6440],
        [1.4752, 1.9067, 1.4434],
        [1.3311, 1.3418, 1.5698]])


##### 语法3：in-place（*将一个tensor加到另一个tensor上，改变运算对象*）

In [14]:
y.add_(x)
print(y)

tensor([[1.8134, 1.6335, 1.5455],
        [1.9205, 1.1435, 1.8571],
        [1.9714, 1.1670, 1.6440],
        [1.4752, 1.9067, 1.4434],
        [1.3311, 1.3418, 1.5698]])


任何以**"_"结尾**的操作都会替换原变量，如：*x.copy_(y),x.t_()*都会改变x

tensor可采用类似numpy的slice, 索引方式相同(*各维度用“，”分隔，对每一维度，start:end:step包含start不包含end*)

In [17]:
print(y)
print(y[:,1])
print(y[1,:])
print(y[:,-1])
print(y[2:4,-1])
print(y[0:4:2,1:3])

tensor([[1.8134, 1.6335, 1.5455],
        [1.9205, 1.1435, 1.8571],
        [1.9714, 1.1670, 1.6440],
        [1.4752, 1.9067, 1.4434],
        [1.3311, 1.3418, 1.5698]])
tensor([1.6335, 1.1435, 1.1670, 1.9067, 1.3418])
tensor([1.9205, 1.1435, 1.8571])
tensor([1.5455, 1.8571, 1.6440, 1.4434, 1.5698])
tensor([1.6440, 1.4434])
tensor([[1.6335, 1.5455],
        [1.1670, 1.6440]])
