## **昨天没走完**，今天继续根据PyTorch教程中的60min Blitz走一遭
#### *结果今天摸了一整天的🐟*

In [2]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

### What is PyTorch?
#### Operations

from \_\_future__ import print_function 使得在Python 2中print函数也得加（）

In [5]:
from __future__ import print_function
import torch

torch.view: *resize/reshape tensor*, 参数-1表示该参数由维度推断得来

In [8]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
t=x.view(1,-1)
print(x)
print(y)
print(z)
print(t)

tensor([[ 0.1815, -0.6658, -0.1449,  0.9833],
        [ 0.3941, -0.3346,  0.9866, -0.3663],
        [ 0.5880,  0.0405,  0.0253,  1.5809],
        [-0.3907,  0.3668,  0.8283,  0.3876]])
tensor([ 0.1815, -0.6658, -0.1449,  0.9833,  0.3941, -0.3346,  0.9866, -0.3663,
         0.5880,  0.0405,  0.0253,  1.5809, -0.3907,  0.3668,  0.8283,  0.3876])
tensor([[ 0.1815, -0.6658, -0.1449,  0.9833,  0.3941, -0.3346,  0.9866, -0.3663],
        [ 0.5880,  0.0405,  0.0253,  1.5809, -0.3907,  0.3668,  0.8283,  0.3876]])
tensor([[ 0.1815, -0.6658, -0.1449,  0.9833,  0.3941, -0.3346,  0.9866, -0.3663,
          0.5880,  0.0405,  0.0253,  1.5809, -0.3907,  0.3668,  0.8283,  0.3876]])


In [11]:
m=torch.randn(2,3,4)
n=m.view(-1,2,4)
print(m.size(), n.size())

torch.Size([2, 3, 4]) torch.Size([3, 2, 4])


对于只有一个元素的tensor，使用.item()可以获取该元素的值

In [16]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([1.2182])
1.218241572380066


In [17]:
y=torch.randn(2,4)
print(y[1,3])
print(y[1,3].item())

tensor(-0.4541)
-0.45413321256637573


#### Numpy Bridge

Torch tensor与numpy array共享底层内存地址（*如果torch tensor位于CPU*），修改一个将会导致另一个变化

将torch tensor转换为numpy array

In [21]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


修改其中一个会导致另一个变化

In [22]:
a.add_(2)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


将numpy array转换为torch tensor

In [24]:
import numpy as np
a=np.zeros(4)
b=torch.from_numpy(a)
np.add(a,3,out=a)
print(a)
print(b)


[3. 3. 3. 3.]
tensor([3., 3., 3., 3.], dtype=torch.float64)


#### CUDA Tensors
可以利用.to方法将tensors移动到如何device

In [48]:
# 使用torch.device对象将tensor移入或移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda") #device是一个torch.device对象
    y = torch.ones_like(x,device=device) # 直接在GPU创建tensor
    x = x.to(device) # 或者直接用to("cuda")
    z = x + y
#     a = torch.randn(1)
#     s = a + y
#     直接将cpu中的tensor与gpu中的tensor会报错
#     报错内容:expected device cpu and dtype Float but got device cuda:0 and dtype Long
#     因为_th_normal_ not supported on CPUType for Long
    print(z)
    print(z.to("cpu", torch.double)) # .to方法也能同时改变dtype
#     print(s)
#     print(s.to("cuda"))
#     print(s.to("cpu"))

tensor([[2, 2, 2],
        [2, 2, 2]], device='cuda:0')
tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
